name: Deploy Sanity
on:
    push:
        branches: [master]
jobs:
    sanity_deploy:
        name: Sanity Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: yarn install
            - name: Deploy
              run: |
                  set -e
                  # Make sure to add a secret for SANITY_AUTH_TOKEN
                  SANITY_AUTH_TOKEN="${{ secrets.SANITY_AUTH_TOKEN }}" yarn deploy
